
name: Robot TechXposed

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  crear-y-subir:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Descargar c√≥digo
        uses: actions/checkout@v2

      - name: 2. Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 3. Instalar herramientas
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml
          pip install moviepy==1.0.3 Pillow==9.5.0 decorator imageio imageio-ffmpeg google-api-python-client google-auth-oauthlib requests

      - name: 4. CREAR VIDEO
        run: python generador.py

      - name: 5. SUBIR A YOUTUBE
        env:
          YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
        run: python subir.py
